import type { NextRequest } from "next/server";
import { handle } from "@/lib/server/b/http";
import { supabaseAdmin } from "@/lib/server/b/supabase";

/** Workflow definitions generated by the Executor Agent for a workforce plan. */
export async function GET(req: NextRequest) {
  const workforcePlanId = req.nextUrl.searchParams.get("workforcePlanId");
  return handle(async () => {
    if (!workforcePlanId) throw new Error("workforcePlanId query param is required");
    const { data, error } = await supabaseAdmin()
      .from("workflow_definitions")
      .select("*")
      .eq("workforce_plan_id", workforcePlanId);
    if (error) throw new Error(error.message);
    return { workflowDefinitions: data ?? [] };
  });
}
